name: musicblocks-test

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  musicblocks-docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses musicblocks
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="jleekwong/musicblocks"
          source .github/workflows/utils.sh
          music_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
