name: musicblocks-test

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  musicblocks-docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses musicblocks
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="jleekwong/musicblocks"
          source .github/workflows/utils.sh
          music_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
          music_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $music_arm_sha
          nginx_arm_sha=$(get_manifest_sha "treehouses/nginx:latest" "arm")
          echo $nginx_arm_sha
          flag_arm=$(is_base "treehouses/nginx@"$nginx_arm_sha "$repo@"$music_arm_sha)
          echo $flag_arm
          music_amd64_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo $music_amd64_sha
          nginx_amd64_sha=$(get_manifest_sha "treehouses/nginx:latest" "amd64")
          echo $nginx_amd64_sha
          flag_amd64=$(is_base "treehouses/nginx@"$nginx_amd64_sha "$repo@"$music_amd64_sha)
          echo $flag_amd64
